name: wolnelektury
description: "Aplikacja Wolne Lektury"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.1+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # External libs
  audio_session: 0.2.2
  bloc: ^9.0.0
  cached_network_image: 3.4.1
  collection: ^1.19.1
  connectivity_plus: 6.1.4
  dio: 5.7.0
  drift: 2.26.1
  drift_flutter: 0.2.4
  easy_localization: 3.0.7+1
  file_saver: 0.2.14
  flutter_bloc: ^9.0.0
  flutter_dotenv: 5.2.1
  flutter_hooks: 0.21.2
  flutter_html: 3.0.0-beta.2
  flutter_secure_storage: 9.2.4
  flutter_sticky_header: 0.8.0
  flutter_svg: 2.1.0
  flutter_switch: 0.3.2
  freezed_annotation: 3.0.0
  get_it: 8.0.3
  go_router: 15.1.2
  html: ^0.15.4
  just_audio: 0.10.3
  just_audio_background: ^0.0.1-beta.17
  json_annotation: 4.9.0
  mockito: 5.4.6
  logger: 2.5.0
  url_launcher: 6.3.1
  package_info_plus: 8.3.0
  scroll_to_index: 3.0.1
  scrollable_positioned_list: 0.3.8
  skeletonizer: 2.0.1
  visibility_detector: 0.4.0+2

dev_dependencies:
  build_runner: 2.4.15
  drift_dev: 2.26.1
  freezed: 3.0.6
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_serializable: 6.9.5

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/translations/
    - assets/images/
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/custom_icons/CustomIcons.ttf
    - family: SourceSerif4
      fonts:
        - asset: assets/fonts/SourceSerif4_36pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/SourceSerif4_36pt-SemiBold.ttf
          weight: 600
    - family: SourceSans3
      fonts:
        - asset: assets/fonts/SourceSans3-Regular.ttf
          weight: 400
        - asset: assets/fonts/SourceSans3-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/SourceSans3-Bold.ttf
          weight: 700
        - asset: assets/fonts/SourceSans3-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/SourceSans3-Light.ttf
          weight: 300
        - asset: assets/fonts/SourceSans3-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/SourceSans3-Medium.ttf
          weight: 500
        - asset: assets/fonts/SourceSans3-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/SourceSans3-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SourceSans3-SemiBoldItalic.ttf
          weight: 600
          style: italic
