// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu0oyNtGBzJJ_eMfOjhusEZm9fO5kSY1g',
    appId: '1:858391861699:android:7ab6c226673184191b0576',
    messagingSenderId: '858391861699',
    projectId: 'wolne-lektury-ae928',
    databaseURL: 'https://wolne-lektury-ae928.firebaseio.com',
    storageBucket: 'wolne-lektury-ae928.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxkteg4r7dzab-95f4pasgpMM6x42tV_Q',
    appId: '1:858391861699:ios:441659e5ca3c1c751b0576',
    messagingSenderId: '858391861699',
    projectId: 'wolne-lektury-ae928',
    databaseURL: 'https://wolne-lektury-ae928.firebaseio.com',
    storageBucket: 'wolne-lektury-ae928.firebasestorage.app',
    iosBundleId: 'pl.app.wolnelektury',
  );
}
